// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Scryfall_Admin.Data;

#nullable disable

namespace Scryfall_Admin.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Scryfall_Admin.Models.Carta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColecaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CustoDeMana")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ImagemUrisId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Lealdade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("LegalidadesId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Mana")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Poder")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Raridade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Resistencia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ColecaoId");

                    b.HasIndex("ImagemUrisId");

                    b.HasIndex("LegalidadesId");

                    b.ToTable("Cartas");
                });

            modelBuilder.Entity("Scryfall_Admin.Models.CartaImagensUris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Large")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Normal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Small")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("ImageUris");
                });

            modelBuilder.Entity("Scryfall_Admin.Models.CartaLegalidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Duel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Legacy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Modern")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Pauper")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Predh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Legalidades");
                });

            modelBuilder.Entity("Scryfall_Admin.Models.Colecao", b =>
                {
                    b.Property<int>("ColecaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColecaoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("ColecaoId");

                    b.ToTable("Colecao");
                });

            modelBuilder.Entity("Scryfall_Admin.Models.Carta", b =>
                {
                    b.HasOne("Scryfall_Admin.Models.Colecao", "Colecao")
                        .WithMany("Cartas")
                        .HasForeignKey("ColecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scryfall_Admin.Models.CartaImagensUris", "ImagemUris")
                        .WithMany("Cartas")
                        .HasForeignKey("ImagemUrisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scryfall_Admin.Models.CartaLegalidades", "Legalidades")
                        .WithMany("Cartas")
                        .HasForeignKey("LegalidadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colecao");

                    b.Navigation("ImagemUris");

                    b.Navigation("Legalidades");
                });

            modelBuilder.Entity("Scryfall_Admin.Models.CartaImagensUris", b =>
                {
                    b.Navigation("Cartas");
                });

            modelBuilder.Entity("Scryfall_Admin.Models.CartaLegalidades", b =>
                {
                    b.Navigation("Cartas");
                });

            modelBuilder.Entity("Scryfall_Admin.Models.Colecao", b =>
                {
                    b.Navigation("Cartas");
                });
#pragma warning restore 612, 618
        }
    }
}
